# -*- coding: utf-8 -*-
"""first.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/112eGus3_IqwT3_tx_f8uT8JsnPBI99t-
"""

!pip install openai

from openai import OpenAI

client = OpenAI(api_key="sk-proj-kOO8KSqqfDePIQwh4MegH6uR0Rnqw hSuUF5_gxtSfMvQ_OArV9LbAVRHIILJX SFzGTra3iRI2NT3BlbkFJ82mhZaJrcNdm 6plH4m8xYJ5RyK-caBnz1ILIWMDI6yDtS05q4YtSWtn2qBa XSV_WfSk77P47QA")

# @title
response = client.responses.create(
    model="gpt-4.0-mini",
    input="Write a short note on SAP."
)

print(response)